export const employeeData = [
  { id: 1, name: 'Sarah Johnson', department: 'Engineering', salary: 95000, performance: 4.5, tenure: 5, age: 32, location: 'New York' },
  { id: 2, name: 'Michael Chen', department: 'Engineering', salary: 110000, performance: 4.8, tenure: 7, age: 35, location: 'San Francisco' },
  { id: 3, name: 'Emily Rodriguez', department: 'Sales', salary: 78000, performance: 4.2, tenure: 3, age: 28, location: 'Chicago' },
  { id: 4, name: 'James Williams', department: 'Sales', salary: 85000, performance: 4.6, tenure: 4, age: 30, location: 'New York' },
  { id: 5, name: 'Lisa Anderson', department: 'Marketing', salary: 72000, performance: 4.0, tenure: 2, age: 26, location: 'Los Angeles' },
  { id: 6, name: 'David Kim', department: 'Engineering', salary: 105000, performance: 4.7, tenure: 6, age: 33, location: 'San Francisco' },
  { id: 7, name: 'Maria Garcia', department: 'HR', salary: 68000, performance: 4.3, tenure: 4, age: 29, location: 'Chicago' },
  { id: 8, name: 'Robert Taylor', department: 'Sales', salary: 92000, performance: 4.9, tenure: 8, age: 37, location: 'New York' },
  { id: 9, name: 'Jennifer Lee', department: 'Engineering', salary: 98000, performance: 4.4, tenure: 5, age: 31, location: 'San Francisco' },
  { id: 10, name: 'Thomas Brown', department: 'Marketing', salary: 75000, performance: 4.1, tenure: 3, age: 27, location: 'Los Angeles' },
  { id: 11, name: 'Amanda White', department: 'Sales', salary: 88000, performance: 4.5, tenure: 6, age: 34, location: 'Chicago' },
  { id: 12, name: 'Christopher Davis', department: 'Engineering', salary: 115000, performance: 4.9, tenure: 9, age: 38, location: 'San Francisco' },
  { id: 13, name: 'Jessica Martinez', department: 'HR', salary: 71000, performance: 4.2, tenure: 3, age: 28, location: 'New York' },
  { id: 14, name: 'Daniel Wilson', department: 'Marketing', salary: 79000, performance: 4.4, tenure: 4, age: 30, location: 'Los Angeles' },
  { id: 15, name: 'Michelle Thompson', department: 'Sales', salary: 86000, performance: 4.6, tenure: 5, age: 32, location: 'Chicago' },
  { id: 16, name: 'Kevin Moore', department: 'Engineering', salary: 102000, performance: 4.7, tenure: 7, age: 36, location: 'San Francisco' },
  { id: 17, name: 'Laura Jackson', department: 'HR', salary: 69000, performance: 4.0, tenure: 2, age: 25, location: 'New York' },
  { id: 18, name: 'Brian Martin', department: 'Marketing', salary: 77000, performance: 4.3, tenure: 4, age: 29, location: 'Los Angeles' },
  { id: 19, name: 'Nicole Harris', department: 'Sales', salary: 91000, performance: 4.8, tenure: 7, age: 35, location: 'Chicago' },
  { id: 20, name: 'Ryan Clark', department: 'Engineering', salary: 108000, performance: 4.6, tenure: 6, age: 33, location: 'San Francisco' },
];