export const trainingData = [
  {
    "Associate ID": "A10000",
    "First Name": "Kelly",
    "Last Name": "Hughes",
    "Full Name": "Kelly Hughes",
    Country: "Australia",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Managerial",
    Theme: "Advanced Leadership Skills",
    "Training Hours": 1.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10001",
    "First Name": "Dwayne",
    "Last Name": "Butler",
    "Full Name": "Dwayne Butler",
    Country: "Canada",
    Region: "North America",
    "Department description": "Analytics",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Data Analytics Fundamentals",
    "Training Hours": 2,
    "Course In Scope": "No",
    "Manager Full Name": "Mark Richardson",
  },
  {
    "Associate ID": "A10002",
    "First Name": "Grace",
    "Last Name": "Cooper",
    "Full Name": "Grace Cooper",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Analytics",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Financial Modeling",
    "Training Hours": 0,
    "Course In Scope": "No",
    "Manager Full Name": "Jennifer Barnes",
  },
  {
    "Associate ID": "A10003",
    "First Name": "Michael",
    "Last Name": "Chen",
    "Full Name": "Michael Chen",
    Country: "USA",
    Region: "North America",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Cloud Architecture",
    "Training Hours": 3.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10004",
    "First Name": "Priya",
    "Last Name": "Sharma",
    "Full Name": "Priya Sharma",
    Country: "India",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Strategic Selling",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10005",
    "First Name": "Emma",
    "Last Name": "Wilson",
    "Full Name": "Emma Wilson",
    Country: "UK",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Talent Management",
    "Training Hours": 1.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "James Brown",
  },
  {
    "Associate ID": "A10006",
    "First Name": "Carlos",
    "Last Name": "Rodriguez",
    "Full Name": "Carlos Rodriguez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Process Optimization",
    "Training Hours": 4.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10007",
    "First Name": "Li",
    "Last Name": "Wang",
    "Full Name": "Li Wang",
    Country: "China",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Cybersecurity Essentials",
    "Training Hours": 3.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10008",
    "First Name": "Sophie",
    "Last Name": "Martin",
    "Full Name": "Sophie Martin",
    Country: "France",
    Region: "EMEA",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Digital Marketing Strategy",
    "Training Hours": 0.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10009",
    "First Name": "Ahmed",
    "Last Name": "Hassan",
    "Full Name": "Ahmed Hassan",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Executive Leadership",
    "Training Hours": 2.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10010",
    "First Name": "Maria",
    "Last Name": "Silva",
    "Full Name": "Maria Silva",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Customer Relationship Management",
    "Training Hours": 3.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10011",
    "First Name": "Yuki",
    "Last Name": "Tanaka",
    "Full Name": "Yuki Tanaka",
    Country: "Japan",
    Region: "APAC",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Machine Learning Basics",
    "Training Hours": 4.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10012",
    "First Name": "Anna",
    "Last Name": "Schmidt",
    "Full Name": "Anna Schmidt",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Business Intelligence",
    "Training Hours": 2.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10013",
    "First Name": "David",
    "Last Name": "Lee",
    "Full Name": "David Lee",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "DevOps Practices",
    "Training Hours": 3.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10014",
    "First Name": "Isabella",
    "Last Name": "Rossi",
    "Full Name": "Isabella Rossi",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Performance Management",
    "Training Hours": 0.8,
    "Course In Scope": "No",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10030",
    "First Name": "Hana",
    "Last Name": "Kim",
    "Full Name": "Hana Kim",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Corporate Finance",
    "Training Hours": 2.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10031",
    "First Name": "Thomas",
    "Last Name": "Anderson",
    "Full Name": "Thomas Anderson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Software Architecture",
    "Training Hours": 4.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10032",
    "First Name": "Layla",
    "Last Name": "Ali",
    "Full Name": "Layla Ali",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    "Theme": "Recruitment Strategies",
    "Training Hours": 0.4,
    "Course In Scope": "No",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10033",
    "First Name": "Ryan",
    "Last Name": "Murphy",
    "Full Name": "Ryan Murphy",
    Country: "USA",
    Region: "North America",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Sales Leadership",
    "Training Hours": 3.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10034",
    "First Name": "Ava",
    "Last Name": "Thompson",
    "Full Name": "Ava Thompson",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Data Visualization",
    "Training Hours": 1.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10035",
    "First Name": "Pierre",
    "Last Name": "Laurent",
    "Full Name": "Pierre Laurent",
    Country: "France",
    Region: "EMEA",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Cloud Computing",
    "Training Hours": 3.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10036",
    "First Name": "Ravi",
    "Last Name": "Patel",
    "Full Name": "Ravi Patel",
    Country: "India",
    Region: "APAC",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Lean Management",
    "Training Hours": 2.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10037",
    "First Name": "Charlotte",
    "Last Name": "Williams",
    "Full Name": "Charlotte Williams",
    Country: "UK",
    Region: "EMEA",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "SEO Optimization",
    "Training Hours": 2.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "James Brown",
  },
  {
    "Associate ID": "A10038",
    "First Name": "Juan",
    "Last Name": "Hernandez",
    "Full Name": "Juan Hernandez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Investment Analysis",
    "Training Hours": 0.7,
    "Course In Scope": "No",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10039",
    "First Name": "Kenji",
    "Last Name": "Nakamura",
    "Full Name": "Kenji Nakamura",
    Country: "Japan",
    Region: "APAC",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "API Design",
    "Training Hours": 4.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10040",
    "First Name": "Sophia",
    "Last Name": "Müller",
    "Full Name": "Sophia Müller",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Product Knowledge",
    "Training Hours": 1.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10041",
    "First Name": "Jackson",
    "Last Name": "Brown",
    "Full Name": "Jackson Brown",
    Country: "Canada",
    Region: "North America",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Compensation Management",
    "Training Hours": 3.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10042",
    "First Name": "Wei",
    "Last Name": "Chen",
    "Full Name": "Wei Chen",
    Country: "China",
    Region: "APAC",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Statistical Analysis",
    "Training Hours": 3.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10043",
    "First Name": "Amelia",
    "Last Name": "Garcia",
    "Full Name": "Amelia Garcia",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Email Marketing",
    "Training Hours": 1.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10044",
    "First Name": "Hassan",
    "Last Name": "Rahman",
    "Full Name": "Hassan Rahman",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "IT Service Management",
    "Training Hours": 0.9,
    "Course In Scope": "No",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10045",
    "First Name": "Mia",
    "Last Name": "Anderson",
    "Full Name": "Mia Anderson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Project Management",
    "Training Hours": 3.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10046",
    "First Name": "Arjun",
    "Last Name": "Singh",
    "Full Name": "Arjun Singh",
    Country: "India",
    Region: "APAC",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Microservices Architecture",
    "Training Hours": 2.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10047",
    "First Name": "Giulia",
    "Last Name": "Romano",
    "Full Name": "Giulia Romano",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Strategic Planning",
    "Training Hours": 3.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10048",
    "First Name": "Ethan",
    "Last Name": "Miller",
    "Full Name": "Ethan Miller",
    Country: "USA",
    Region: "North America",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Cold Calling Techniques",
    "Training Hours": 0.5,
    "Course In Scope": "No",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10049",
    "First Name": "Yuna",
    "Last Name": "Park",
    "Full Name": "Yuna Park",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Marketing Automation",
    "Training Hours": 3.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10050",
    "First Name": "Noah",
    "Last Name": "Wilson",
    "Full Name": "Noah Wilson",
    Country: "Australia",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Infrastructure Management",
    "Training Hours": 2.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10051",
    "First Name": "Camille",
    "Last Name": "Dubois",
    "Full Name": "Camille Dubois",
    Country: "France",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Training & Development",
    "Training Hours": 2.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10052",
    "First Name": "Daniel",
    "Last Name": "Santos",
    "Full Name": "Daniel Santos",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Change Management",
    "Training Hours": 2.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10053",
    "First Name": "Amir",
    "Last Name": "Khalil",
    "Full Name": "Amir Khalil",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Big Data Analytics",
    "Training Hours": 0.6,
    "Course In Scope": "No",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10054",
    "First Name": "Emma",
    "Last Name": "Schmidt",
    "Full Name": "Emma Schmidt",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Quality Assurance",
    "Training Hours": 4.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10055",
    "First Name": "Liam",
    "Last Name": "MacDonald",
    "Full Name": "Liam MacDonald",
    Country: "Canada",
    Region: "North America",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Cost Management",
    "Training Hours": 1.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10056",
    "First Name": "Jing",
    "Last Name": "Liu",
    "Full Name": "Jing Liu",
    Country: "China",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "B2B Sales",
    "Training Hours": 3.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10057",
    "First Name": "Isabella",
    "Last Name": "Martinez",
    "Full Name": "Isabella Martinez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Influencer Marketing",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10058",
    "First Name": "Takeshi",
    "Last Name": "Suzuki",
    "Full Name": "Takeshi Suzuki",
    Country: "Japan",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Blockchain Technology",
    "Training Hours": 0.8,
    "Course In Scope": "No",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10059",
    "First Name": "Fatima",
    "Last Name": "Al-Rashid",
    "Full Name": "Fatima Al-Rashid",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Diversity & Inclusion",
    "Training Hours": 2.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10060",
    "First Name": "Oscar",
    "Last Name": "Johansson",
    "Full Name": "Oscar Johansson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Machine Learning Applications",
    "Training Hours": 4.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10061",
    "First Name": "Priya",
    "Last Name": "Gupta",
    "Full Name": "Priya Gupta",
    Country: "India",
    Region: "APAC",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Managerial",
    Theme: "Risk Management",
    "Training Hours": 2.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10062",
    "First Name": "Alessandro",
    "Last Name": "Conti",
    "Full Name": "Alessandro Conti",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Frontend Development",
    "Training Hours": 3.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10063",
    "First Name": "Madison",
    "Last Name": "Clark",
    "Full Name": "Madison Clark",
    Country: "USA",
    Region: "North America",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Treasury Management",
    "Training Hours": 0.4,
    "Course In Scope": "No",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10064",
    "First Name": "Min-Jun",
    "Last Name": "Choi",
    "Full Name": "Min-Jun Choi",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Sales Forecasting",
    "Training Hours": 2.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10065",
    "First Name": "Chloe",
    "Last Name": "White",
    "Full Name": "Chloe White",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Customer Analytics",
    "Training Hours": 2.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10066",
    "First Name": "Julien",
    "Last Name": "Bernard",
    "Full Name": "Julien Bernard",
    Country: "France",
    Region: "EMEA",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "System Administration",
    "Training Hours": 3.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10067",
    "First Name": "Gabriel",
    "Last Name": "Oliveira",
    "Full Name": "Gabriel Oliveira",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Organizational Development",
    "Training Hours": 0.7,
    "Course In Scope": "No",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10068",
    "First Name": "Laila",
    "Last Name": "Mansour",
    "Full Name": "Laila Mansour",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "AI & Automation",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10069",
    "First Name": "Felix",
    "Last Name": "Wagner",
    "Full Name": "Felix Wagner",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Quality Management",
    "Training Hours": 3.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10070",
    "First Name": "Sarah",
    "Last Name": "Martin",
    "Full Name": "Sarah Martin",
    Country: "Canada",
    Region: "North America",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Mobile App Development",
    "Training Hours": 1.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10071",
    "First Name": "Xiao",
    "Last Name": "Wang",
    "Full Name": "Xiao Wang",
    Country: "China",
    Region: "APAC",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "International Finance",
    "Training Hours": 3.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10072",
    "First Name": "Rosa",
    "Last Name": "Lopez",
    "Full Name": "Rosa Lopez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Territory Management",
    "Training Hours": 0.5,
    "Course In Scope": "No",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10073",
    "First Name": "Akira",
    "Last Name": "Watanabe",
    "Full Name": "Akira Watanabe",
    Country: "Japan",
    Region: "APAC",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Product Marketing",
    "Training Hours": 3.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10074",
    "First Name": "Omar",
    "Last Name": "Hassan",
    "Full Name": "Omar Hassan",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Data Security",
    "Training Hours": 2.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10075",
    "First Name": "Astrid",
    "Last Name": "Nilsson",
    "Full Name": "Astrid Nilsson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Leadership Coaching",
    "Training Hours": 2.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10076",
    "First Name": "Vikram",
    "Last Name": "Reddy",
    "Full Name": "Vikram Reddy",
    Country: "India",
    Region: "APAC",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Deep Learning",
    "Training Hours": 0.9,
    "Course In Scope": "No",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10077",
    "First Name": "Francesca",
    "Last Name": "Ricci",
    "Full Name": "Francesca Ricci",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Continuous Improvement",
    "Training Hours": 2.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10078",
    "First Name": "William",
    "Last Name": "Harris",
    "Full Name": "William Harris",
    Country: "USA",
    Region: "North America",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Backend Development",
    "Training Hours": 4.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10079",
    "First Name": "Ji-Woo",
    "Last Name": "Lee",
    "Full Name": "Ji-Woo Lee",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Mergers & Acquisitions",
    "Training Hours": 1.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10080",
    "First Name": "Lily",
    "Last Name": "Robinson",
    "Full Name": "Lily Robinson",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Consultative Selling",
    "Training Hours": 3.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10081",
    "First Name": "Antoine",
    "Last Name": "Moreau",
    "Full Name": "Antoine Moreau",
    Country: "France",
    Region: "EMEA",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Video Marketing",
    "Training Hours": 0.6,
    "Course In Scope": "No",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10082",
    "First Name": "Rafael",
    "Last Name": "Pereira",
    "Full Name": "Rafael Pereira",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Virtualization",
    "Training Hours": 3.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10083",
    "First Name": "Nour",
    "Last Name": "Abdel",
    "Full Name": "Nour Abdel",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Conflict Resolution",
    "Training Hours": 2.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10084",
    "First Name": "Lukas",
    "Last Name": "Fischer",
    "Full Name": "Lukas Fischer",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Python for Data Science",
    "Training Hours": 4.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10085",
    "First Name": "Emily",
    "Last Name": "Campbell",
    "Full Name": "Emily Campbell",
    Country: "Canada",
    Region: "North America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Managerial",
    Theme: "Vendor Management",
    "Training Hours": 0.8,
    "Course In Scope": "No",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10086",
    "First Name": "Yang",
    "Last Name": "Li",
    "Full Name": "Yang Li",
    Country: "China",
    Region: "APAC",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Containerization",
    "Training Hours": 2.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10087",
    "First Name": "Valentina",
    "Last Name": "Flores",
    "Full Name": "Valentina Flores",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Audit & Compliance",
    "Training Hours": 3.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10088",
    "First Name": "Haruto",
    "Last Name": "Ito",
    "Full Name": "Haruto Ito",
    Country: "Japan",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Sales Enablement",
    "Training Hours": 2.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10089",
    "First Name": "Mariam",
    "Last Name": "Al-Farsi",
    "Full Name": "Mariam Al-Farsi",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Growth Hacking",
    "Training Hours": 1.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10090",
    "First Name": "Elsa",
    "Last Name": "Bergstrom",
    "Full Name": "Elsa Bergstrom",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "IoT Solutions",
    "Training Hours": 0.7,
    "Course In Scope": "No",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10091",
    "First Name": "Rohan",
    "Last Name": "Nair",
    "Full Name": "Rohan Nair",
    Country: "India",
    Region: "APAC",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Change Leadership",
    "Training Hours": 3.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10092",
    "First Name": "Chiara",
    "Last Name": "Gallo",
    "Full Name": "Chiara Gallo",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "R Programming",
    "Training Hours": 2.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10093",
    "First Name": "Alexander",
    "Last Name": "Moore",
    "Full Name": "Alexander Moore",
    Country: "USA",
    Region: "North America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Six Sigma",
    "Training Hours": 4.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10094",
    "First Name": "Seo-Jun",
    "Last Name": "Kim",
    "Full Name": "Seo-Jun Kim",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "UI/UX Design",
    "Training Hours": 0.5,
    "Course In Scope": "No",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10095",
    "First Name": "Harper",
    "Last Name": "Taylor",
    "Full Name": "Harper Taylor",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Tax Planning",
    "Training Hours": 3.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10096",
    "First Name": "Léa",
    "Last Name": "Petit",
    "Full Name": "Léa Petit",
    Country: "France",
    Region: "EMEA",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Pricing Strategies",
    "Training Hours": 2.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10097",
    "First Name": "Mateo",
    "Last Name": "Rodrigues",
    "Full Name": "Mateo Rodrigues",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Public Relations",
    "Training Hours": 2.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10098",
    "First Name": "Yasmin",
    "Last Name": "Fahmy",
    "Full Name": "Yasmin Fahmy",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Ethical Hacking",
    "Training Hours": 0.6,
    "Course In Scope": "No",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10099",
    "First Name": "Maximilian",
    "Last Name": "Becker",
    "Full Name": "Maximilian Becker",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Support",
    Theme: "Succession Planning",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10100",
    "First Name": "Avery",
    "Last Name": "Lewis",
    "Full Name": "Avery Lewis",
    Country: "Canada",
    Region: "North America",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Tableau Visualization",
    "Training Hours": 3.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10101",
    "First Name": "Lian",
    "Last Name": "Zhou",
    "Full Name": "Lian Zhou",
    Country: "China",
    Region: "APAC",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Managerial",
    Theme: "Logistics Management",
    "Training Hours": 1.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10102",
    "First Name": "Sofia",
    "Last Name": "Gomez",
    "Full Name": "Sofia Gomez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Test Automation",
    "Training Hours": 4.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10103",
    "First Name": "Ren",
    "Last Name": "Takahashi",
    "Full Name": "Ren Takahashi",
    Country: "Japan",
    Region: "APAC",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Credit Analysis",
    "Training Hours": 0.8,
    "Course In Scope": "No",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10104",
    "First Name": "Khalid",
    "Last Name": "Ahmed",
    "Full Name": "Khalid Ahmed",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Channel Sales",
    "Training Hours": 3.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10105",
    "First Name": "Ingrid",
    "Last Name": "Larsson",
    "Full Name": "Ingrid Larsson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Event Marketing",
    "Training Hours": 2.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10106",
    "First Name": "Aditya",
    "Last Name": "Kapoor",
    "Full Name": "Aditya Kapoor",
    Country: "India",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Kubernetes",
    "Training Hours": 4.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10107",
    "First Name": "Bianca",
    "Last Name": "Esposito",
    "Full Name": "Bianca Esposito",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Workplace Wellness",
    "Training Hours": 0.9,
    "Course In Scope": "No",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10108",
    "First Name": "Logan",
    "Last Name": "Mitchell",
    "Full Name": "Logan Mitchell",
    Country: "USA",
    Region: "North America",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Power BI",
    "Training Hours": 2.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10109",
    "First Name": "Da-Eun",
    "Last Name": "Yoon",
    "Full Name": "Da-Eun Yoon",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Business Process Reengineering",
    "Training Hours": 3.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10110",
    "First Name": "Ruby",
    "Last Name": "Watson",
    "Full Name": "Ruby Watson",
    Country: "UK",
    Region: "EMEA",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Full Stack Development",
    "Training Hours": 4.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "James Brown",
  },
  {
    "Associate ID": "A10015",
    "First Name": "James",
    "Last Name": "Taylor",
    "Full Name": "James Taylor",
    Country: "Canada",
    Region: "North America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Team Leadership",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10016",
    "First Name": "Fatima",
    "Last Name": "Ahmed",
    "Full Name": "Fatima Ahmed",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Brand Management",
    "Training Hours": 3.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10017",
    "First Name": "Lars",
    "Last Name": "Andersson",
    "Full Name": "Lars Andersson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Financial Risk Management",
    "Training Hours": 2.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10018",
    "First Name": "Olivia",
    "Last Name": "Brown",
    "Full Name": "Olivia Brown",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Negotiation Skills",
    "Training Hours": 1.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10019",
    "First Name": "Nathan",
    "Last Name": "White",
    "Full Name": "Nathan White",
    Country: "USA",
    Region: "North America",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Network Security",
    "Training Hours": 3.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10020",
    "First Name": "Aisha",
    "Last Name": "Mohammed",
    "Full Name": "Aisha Mohammed",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Social Media Marketing",
    "Training Hours": 1.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10021",
    "First Name": "Lucas",
    "Last Name": "Costa",
    "Full Name": "Lucas Costa",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Sales Analytics",
    "Training Hours": 2.6,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10022",
    "First Name": "Mei",
    "Last Name": "Zhang",
    "Full Name": "Mei Zhang",
    Country: "China",
    Region: "APAC",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Budget Planning",
    "Training Hours": 0.3,
    "Course In Scope": "No",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10023",
    "First Name": "Oliver",
    "Last Name": "Johnson",
    "Full Name": "Oliver Johnson",
    Country: "UK",
    Region: "EMEA",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Supply Chain Management",
    "Training Hours": 3.4,
    "Course In Scope": "Yes",
    "Manager Full Name": "James Brown",
  },
  {
    "Associate ID": "A10024",
    "First Name": "Sakura",
    "Last Name": "Yamamoto",
    "Full Name": "Sakura Yamamoto",
    Country: "Japan",
    Region: "APAC",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Employee Engagement",
    "Training Hours": 2.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10025",
    "First Name": "Diego",
    "Last Name": "Martinez",
    "Full Name": "Diego Martinez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Agile Development",
    "Training Hours": 4.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10026",
    "First Name": "Nina",
    "Last Name": "Petrov",
    "Full Name": "Nina Petrov",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Predictive Analytics",
    "Training Hours": 3.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10027",
    "First Name": "Benjamin",
    "Last Name": "Davis",
    "Full Name": "Benjamin Davis",
    Country: "Canada",
    Region: "North America",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Database Management",
    "Training Hours": 2.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10028",
    "First Name": "Zara",
    "Last Name": "Khan",
    "Full Name": "Zara Khan",
    Country: "India",
    Region: "APAC",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Content Marketing",
    "Training Hours": 0.6,
    "Course In Scope": "No",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10029",
    "First Name": "Luca",
    "Last Name": "Ferrari",
    "Full Name": "Luca Ferrari",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Account Management",
    "Training Hours": 3.1,
    "Course In Scope": "Yes",
    "Manager Full Name": "Marco Bianchi",
  },
]

// Country coordinates

// export const trainingData = [
//   {
//     "Associate ID": "A10000",
//     "First Name": "Kelly",
//     "Last Name": "Hughes",
//     "Full Name": "Kelly Hughes",
//     Country: "Australia",
//     Region: "APAC",
//     "Department description": "IT",
//     "Job Function": "Marketing",
//     "Job Family": "Marketing Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Managerial",
//     Theme: "Leadership",
//     "Training Hours": 1.5,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "David Walker",
//   },
//   {
//     "Associate ID": "A10001",
//     "First Name": "Dwayne",
//     "Last Name": "Butler",
//     "Full Name": "Dwayne Butler",
//     Country: "Canada",
//     Region: "North America",
//     "Department description": "Analytics",
//     "Job Function": "Operations",
//     "Job Family": "Operations Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Support",
//     Theme: "Technical",
//     "Training Hours": 2,
//     "Course In Scope": "No",
//     "Manager Full Name": "Mark Richardson",
//   },
//   {
//     "Associate ID": "A10002",
//     "First Name": "Grace",
//     "Last Name": "Cooper",
//     "Full Name": "Grace Cooper",
//     Country: "Australia",
//     Region: "APAC",
//     "Department description": "Analytics",
//     "Job Function": "Finance",
//     "Job Family": "Finance Family",
//     "Item Status": "Overdue",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Leadership",
//     Theme: "Technical",
//     "Training Hours": 0,
//     "Course In Scope": "No",
//     "Manager Full Name": "Jennifer Barnes",
//   },
//   {
//     "Associate ID": "A10003",
//     "First Name": "Michael",
//     "Last Name": "Chen",
//     "Full Name": "Michael Chen",
//     Country: "USA",
//     Region: "North America",
//     "Department description": "Engineering",
//     "Job Function": "Technology",
//     "Job Family": "Engineering Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Technical",
//     Theme: "Technical",
//     "Training Hours": 3.5,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Sarah Johnson",
//   },
//   {
//     "Associate ID": "A10004",
//     "First Name": "Priya",
//     "Last Name": "Sharma",
//     "Full Name": "Priya Sharma",
//     Country: "India",
//     Region: "APAC",
//     "Department description": "Sales",
//     "Job Function": "Sales",
//     "Job Family": "Sales Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Sales",
//     Theme: "Leadership",
//     "Training Hours": 2.5,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Raj Kumar",
//   },
//   {
//     "Associate ID": "A10005",
//     "First Name": "Emma",
//     "Last Name": "Wilson",
//     "Full Name": "Emma Wilson",
//     Country: "UK",
//     Region: "EMEA",
//     "Department description": "HR",
//     "Job Function": "Human Resources",
//     "Job Family": "HR Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Support",
//     Theme: "Leadership",
//     "Training Hours": 1.8,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "James Brown",
//   },
//   {
//     "Associate ID": "A10006",
//     "First Name": "Carlos",
//     "Last Name": "Rodriguez",
//     "Full Name": "Carlos Rodriguez",
//     Country: "Mexico",
//     Region: "Latin America",
//     "Department description": "Operations",
//     "Job Function": "Operations",
//     "Job Family": "Operations Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Managerial",
//     Theme: "Technical",
//     "Training Hours": 4.0,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Maria Garcia",
//   },
//   {
//     "Associate ID": "A10007",
//     "First Name": "Li",
//     "Last Name": "Wang",
//     "Full Name": "Li Wang",
//     Country: "China",
//     Region: "APAC",
//     "Department description": "IT",
//     "Job Function": "Technology",
//     "Job Family": "IT Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Technical",
//     Theme: "Technical",
//     "Training Hours": 3.2,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Zhang Wei",
//   },
//   {
//     "Associate ID": "A10008",
//     "First Name": "Sophie",
//     "Last Name": "Martin",
//     "Full Name": "Sophie Martin",
//     Country: "France",
//     Region: "EMEA",
//     "Department description": "Marketing",
//     "Job Function": "Marketing",
//     "Job Family": "Marketing Family",
//     "Item Status": "Overdue",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Sales",
//     Theme: "Leadership",
//     "Training Hours": 0.5,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Pierre Dubois",
//   },
//   {
//     "Associate ID": "A10009",
//     "First Name": "Ahmed",
//     "Last Name": "Hassan",
//     "Full Name": "Ahmed Hassan",
//     Country: "UAE",
//     Region: "Middle East",
//     "Department description": "Finance",
//     "Job Function": "Finance",
//     "Job Family": "Finance Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Leadership",
//     Theme: "Leadership",
//     "Training Hours": 2.8,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Omar Ali",
//   },
//   {
//     "Associate ID": "A10010",
//     "First Name": "Maria",
//     "Last Name": "Silva",
//     "Full Name": "Maria Silva",
//     Country: "Brazil",
//     Region: "Latin America",
//     "Department description": "Sales",
//     "Job Function": "Sales",
//     "Job Family": "Sales Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Sales",
//     Theme: "Technical",
//     "Training Hours": 3.8,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Paulo Santos",
//   },
//   {
//     "Associate ID": "A10011",
//     "First Name": "Yuki",
//     "Last Name": "Tanaka",
//     "Full Name": "Yuki Tanaka",
//     Country: "Japan",
//     Region: "APAC",
//     "Department description": "Engineering",
//     "Job Function": "Technology",
//     "Job Family": "Engineering Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Technical",
//     Theme: "Technical",
//     "Training Hours": 4.5,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Hiroshi Sato",
//   },
//   {
//     "Associate ID": "A10012",
//     "First Name": "Anna",
//     "Last Name": "Schmidt",
//     "Full Name": "Anna Schmidt",
//     Country: "Germany",
//     Region: "EMEA",
//     "Department description": "Analytics",
//     "Job Function": "Analytics",
//     "Job Family": "Analytics Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Technical",
//     Theme: "Technical",
//     "Training Hours": 2.2,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Hans Mueller",
//   },
//   {
//     "Associate ID": "A10013",
//     "First Name": "David",
//     "Last Name": "Lee",
//     "Full Name": "David Lee",
//     Country: "South Korea",
//     Region: "APAC",
//     "Department description": "IT",
//     "Job Function": "Technology",
//     "Job Family": "IT Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Technical",
//     Theme: "Technical",
//     "Training Hours": 3.0,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Kim Park",
//   },
//   {
//     "Associate ID": "A10014",
//     "First Name": "Isabella",
//     "Last Name": "Rossi",
//     "Full Name": "Isabella Rossi",
//     Country: "Italy",
//     Region: "EMEA",
//     "Department description": "HR",
//     "Job Function": "Human Resources",
//     "Job Family": "HR Family",
//     "Item Status": "Overdue",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Support",
//     Theme: "Leadership",
//     "Training Hours": 0.8,
//     "Course In Scope": "No",
//     "Manager Full Name": "Marco Bianchi",
//   },
//   {
//     "Associate ID": "A10015",
//     "First Name": "James",
//     "Last Name": "Taylor",
//     "Full Name": "James Taylor",
//     Country: "Canada",
//     Region: "North America",
//     "Department description": "Operations",
//     "Job Function": "Operations",
//     "Job Family": "Operations Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Managerial",
//     Theme: "Leadership",
//     "Training Hours": 2.5,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Robert Smith",
//   },
//   {
//     "Associate ID": "A10016",
//     "First Name": "Fatima",
//     "Last Name": "Ahmed",
//     "Full Name": "Fatima Ahmed",
//     Country: "Egypt",
//     Region: "Middle East",
//     "Department description": "Marketing",
//     "Job Function": "Marketing",
//     "Job Family": "Marketing Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Sales",
//     Theme: "Leadership",
//     "Training Hours": 3.3,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Mohamed Ibrahim",
//   },
//   {
//     "Associate ID": "A10017",
//     "First Name": "Lars",
//     "Last Name": "Andersson",
//     "Full Name": "Lars Andersson",
//     Country: "Sweden",
//     Region: "EMEA",
//     "Department description": "Finance",
//     "Job Function": "Finance",
//     "Job Family": "Finance Family",
//     "Item Status": "Completed",
//     "Assignment Type": "Mandatory",
//     "Segment (updated)": "Leadership",
//     Theme: "Technical",
//     "Training Hours": 2.9,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "Erik Johansson",
//   },
//   {
//     "Associate ID": "A10018",
//     "First Name": "Olivia",
//     "Last Name": "Brown",
//     "Full Name": "Olivia Brown",
//     Country: "Australia",
//     Region: "APAC",
//     "Department description": "Sales",
//     "Job Function": "Sales",
//     "Job Family": "Sales Family",
//     "Item Status": "In Progress",
//     "Assignment Type": "Optional",
//     "Segment (updated)": "Sales",
//     Theme: "Leadership",
//     "Training Hours": 1.7,
//     "Course In Scope": "Yes",
//     "Manager Full Name": "David Walker",
//   },
// ]

export const countryCoordinates = {
  Australia: { lat: -25.2744, lng: 133.7751 },
  Canada: { lat: 56.1304, lng: -106.3468 },
  USA: { lat: 37.0902, lng: -95.7129 },
  India: { lat: 20.5937, lng: 78.9629 },
  UK: { lat: 55.3781, lng: -3.436 },
  Mexico: { lat: 23.6345, lng: -102.5528 },
  China: { lat: 35.8617, lng: 104.1954 },
  France: { lat: 46.2276, lng: 2.2137 },
  UAE: { lat: 23.4241, lng: 53.8478 },
  Brazil: { lat: -14.235, lng: -51.9253 },
  Japan: { lat: 36.2048, lng: 138.2529 },
  Germany: { lat: 51.1657, lng: 10.4515 },
  "South Korea": { lat: 35.9078, lng: 127.7669 },
  Italy: { lat: 41.8719, lng: 12.5674 },
  Egypt: { lat: 26.8206, lng: 30.8025 },
  Sweden: { lat: 60.1282, lng: 18.6435 },
}