export const trainingData = [
  {
    "Associate ID": "A10000",
    "First Name": "Kelly",
    "Last Name": "Hughes",
    "Full Name": "Kelly Hughes",
    Country: "Australia",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Managerial",
    Theme: "Leadership",
    "Training Hours": 1.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
  {
    "Associate ID": "A10001",
    "First Name": "Dwayne",
    "Last Name": "Butler",
    "Full Name": "Dwayne Butler",
    Country: "Canada",
    Region: "North America",
    "Department description": "Analytics",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Technical",
    "Training Hours": 2,
    "Course In Scope": "No",
    "Manager Full Name": "Mark Richardson",
  },
  {
    "Associate ID": "A10002",
    "First Name": "Grace",
    "Last Name": "Cooper",
    "Full Name": "Grace Cooper",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Analytics",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Leadership",
    Theme: "Technical",
    "Training Hours": 0,
    "Course In Scope": "No",
    "Manager Full Name": "Jennifer Barnes",
  },
  {
    "Associate ID": "A10003",
    "First Name": "Michael",
    "Last Name": "Chen",
    "Full Name": "Michael Chen",
    Country: "USA",
    Region: "North America",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Technical",
    "Training Hours": 3.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Sarah Johnson",
  },
  {
    "Associate ID": "A10004",
    "First Name": "Priya",
    "Last Name": "Sharma",
    "Full Name": "Priya Sharma",
    Country: "India",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Leadership",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Raj Kumar",
  },
  {
    "Associate ID": "A10005",
    "First Name": "Emma",
    "Last Name": "Wilson",
    "Full Name": "Emma Wilson",
    Country: "UK",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Leadership",
    "Training Hours": 1.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "James Brown",
  },
  {
    "Associate ID": "A10006",
    "First Name": "Carlos",
    "Last Name": "Rodriguez",
    "Full Name": "Carlos Rodriguez",
    Country: "Mexico",
    Region: "Latin America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Technical",
    "Training Hours": 4.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Maria Garcia",
  },
  {
    "Associate ID": "A10007",
    "First Name": "Li",
    "Last Name": "Wang",
    "Full Name": "Li Wang",
    Country: "China",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Technical",
    "Training Hours": 3.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Zhang Wei",
  },
  {
    "Associate ID": "A10008",
    "First Name": "Sophie",
    "Last Name": "Martin",
    "Full Name": "Sophie Martin",
    Country: "France",
    Region: "EMEA",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Leadership",
    "Training Hours": 0.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Pierre Dubois",
  },
  {
    "Associate ID": "A10009",
    "First Name": "Ahmed",
    "Last Name": "Hassan",
    "Full Name": "Ahmed Hassan",
    Country: "UAE",
    Region: "Middle East",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Leadership",
    "Training Hours": 2.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Omar Ali",
  },
  {
    "Associate ID": "A10010",
    "First Name": "Maria",
    "Last Name": "Silva",
    "Full Name": "Maria Silva",
    Country: "Brazil",
    Region: "Latin America",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Technical",
    "Training Hours": 3.8,
    "Course In Scope": "Yes",
    "Manager Full Name": "Paulo Santos",
  },
  {
    "Associate ID": "A10011",
    "First Name": "Yuki",
    "Last Name": "Tanaka",
    "Full Name": "Yuki Tanaka",
    Country: "Japan",
    Region: "APAC",
    "Department description": "Engineering",
    "Job Function": "Technology",
    "Job Family": "Engineering Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Technical",
    "Training Hours": 4.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hiroshi Sato",
  },
  {
    "Associate ID": "A10012",
    "First Name": "Anna",
    "Last Name": "Schmidt",
    "Full Name": "Anna Schmidt",
    Country: "Germany",
    Region: "EMEA",
    "Department description": "Analytics",
    "Job Function": "Analytics",
    "Job Family": "Analytics Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Technical",
    Theme: "Technical",
    "Training Hours": 2.2,
    "Course In Scope": "Yes",
    "Manager Full Name": "Hans Mueller",
  },
  {
    "Associate ID": "A10013",
    "First Name": "David",
    "Last Name": "Lee",
    "Full Name": "David Lee",
    Country: "South Korea",
    Region: "APAC",
    "Department description": "IT",
    "Job Function": "Technology",
    "Job Family": "IT Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Technical",
    Theme: "Technical",
    "Training Hours": 3.0,
    "Course In Scope": "Yes",
    "Manager Full Name": "Kim Park",
  },
  {
    "Associate ID": "A10014",
    "First Name": "Isabella",
    "Last Name": "Rossi",
    "Full Name": "Isabella Rossi",
    Country: "Italy",
    Region: "EMEA",
    "Department description": "HR",
    "Job Function": "Human Resources",
    "Job Family": "HR Family",
    "Item Status": "Overdue",
    "Assignment Type": "Optional",
    "Segment (updated)": "Support",
    Theme: "Leadership",
    "Training Hours": 0.8,
    "Course In Scope": "No",
    "Manager Full Name": "Marco Bianchi",
  },
  {
    "Associate ID": "A10015",
    "First Name": "James",
    "Last Name": "Taylor",
    "Full Name": "James Taylor",
    Country: "Canada",
    Region: "North America",
    "Department description": "Operations",
    "Job Function": "Operations",
    "Job Family": "Operations Family",
    "Item Status": "In Progress",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Managerial",
    Theme: "Leadership",
    "Training Hours": 2.5,
    "Course In Scope": "Yes",
    "Manager Full Name": "Robert Smith",
  },
  {
    "Associate ID": "A10016",
    "First Name": "Fatima",
    "Last Name": "Ahmed",
    "Full Name": "Fatima Ahmed",
    Country: "Egypt",
    Region: "Middle East",
    "Department description": "Marketing",
    "Job Function": "Marketing",
    "Job Family": "Marketing Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Sales",
    Theme: "Leadership",
    "Training Hours": 3.3,
    "Course In Scope": "Yes",
    "Manager Full Name": "Mohamed Ibrahim",
  },
  {
    "Associate ID": "A10017",
    "First Name": "Lars",
    "Last Name": "Andersson",
    "Full Name": "Lars Andersson",
    Country: "Sweden",
    Region: "EMEA",
    "Department description": "Finance",
    "Job Function": "Finance",
    "Job Family": "Finance Family",
    "Item Status": "Completed",
    "Assignment Type": "Mandatory",
    "Segment (updated)": "Leadership",
    Theme: "Technical",
    "Training Hours": 2.9,
    "Course In Scope": "Yes",
    "Manager Full Name": "Erik Johansson",
  },
  {
    "Associate ID": "A10018",
    "First Name": "Olivia",
    "Last Name": "Brown",
    "Full Name": "Olivia Brown",
    Country: "Australia",
    Region: "APAC",
    "Department description": "Sales",
    "Job Function": "Sales",
    "Job Family": "Sales Family",
    "Item Status": "In Progress",
    "Assignment Type": "Optional",
    "Segment (updated)": "Sales",
    Theme: "Leadership",
    "Training Hours": 1.7,
    "Course In Scope": "Yes",
    "Manager Full Name": "David Walker",
  },
]

// Country coordinates
export const countryCoordinates = {
  Australia: { lat: -25.2744, lng: 133.7751 },
  Canada: { lat: 56.1304, lng: -106.3468 },
  USA: { lat: 37.0902, lng: -95.7129 },
  India: { lat: 20.5937, lng: 78.9629 },
  UK: { lat: 55.3781, lng: -3.436 },
  Mexico: { lat: 23.6345, lng: -102.5528 },
  China: { lat: 35.8617, lng: 104.1954 },
  France: { lat: 46.2276, lng: 2.2137 },
  UAE: { lat: 23.4241, lng: 53.8478 },
  Brazil: { lat: -14.235, lng: -51.9253 },
  Japan: { lat: 36.2048, lng: 138.2529 },
  Germany: { lat: 51.1657, lng: 10.4515 },
  "South Korea": { lat: 35.9078, lng: 127.7669 },
  Italy: { lat: 41.8719, lng: 12.5674 },
  Egypt: { lat: 26.8206, lng: 30.8025 },
  Sweden: { lat: 60.1282, lng: 18.6435 },
}